package org.omg.IOP;


/**
* org/omg/IOP/ENCODING_CDR_ENCAPS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/openjdk/jdk8u/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, January 30, 2024 5:01:38 AM EST
*/

public interface ENCODING_CDR_ENCAPS
{

  /**
   * The CDR Encapsulation encoding.
   * @see CodecFactory
   */
  public static final short value = (short)(0);
}
