package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_UNIQUENESS_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/openjdk/jdk8u/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, January 30, 2024 5:01:40 AM EST
*/

public interface ID_UNIQUENESS_POLICY_ID
{

  /**
	 * The value representing ID_UNIQUENESS_POLICY_ID.
	 */
  public static final int value = (int)(18L);
}
