package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/UNKNOWN.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/openjdk/jdk8u/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Tuesday, January 30, 2024 5:01:39 AM EST
*/

public interface UNKNOWN
{

  /**
   * XXX
   */
  public static final short value = (short)(5);
}
